require("Comment").setup()
require("elem.autocmds")
require("elem.catppuccino")
require("elem.diffview")
require("elem.indent-blankline")
require("elem.luasnip")
require("elem.neogit")
require("elem.nvim-cmp")
require("elem.plenary")
require("elem.ripple")
require("elem.rust-tools")
require("elem.statusline")
require("elem.telescope")
require("elem.todo-comments")
require("elem.treesitter")
require("elem.winshift")
require("notify").setup({
  background_colour = "#000000",
})
require("elem.noice")
require("fidget").setup()
require("gitsigns").setup()
-- require("hlslens").setup()
require("nvim-web-devicons").setup()
require("treesitter-context").setup()
require("trouble").setup()
